# Generated by Django 3.2.9 on 2021-12-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_feeding_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='feeding',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='toad',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AddField(
            model_name='toad',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
